kind: Deployment
apiVersion: apps/v1
metadata:
   name: dp
spec:
   replicas: 1
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     name: deployment
   template:
     metadata:
       name: dp1
       labels:
         name: deployment
     spec:
      containers:
        - name: dp2
          image: httpd
          ports:
          - containerPort: 80
