---
kind: Pod
apiVersion: v1
metadata:
   name: p2
   labels:
     env: development
     class: pods
spec:
     containers:
        - name: c2
          image: ubuntu
          command: ["/bin/bash", "-c", "while true; do echo welcome; sleep 5 ; done"]
