---
kind: Pod
apiVersion: v1
metadata:
   name: p3
   labels:
     env: development
     class: pods
spec:
     containers:
        - name: c3
          image: ubuntu
          command: ["/bin/bash", "-c", "while true; do echo welcome; sleep 5 ; done"]
     nodeSelector:
        hardware: t2-medium
